#!/usr/bin/env ruby
# frozen_string_literal: true

# Prepare decorative vegetable images for page headers:
# - reads source images from ~/Downloads/vegetables by default, or a directory passed as the first argument;
# - trims transparent padding;
# - centers each vegetable on the same transparent square canvas;
# - writes small transparent WebP images under source/assets/images/vegetables/;
# - regenerates data/vegetables.yml for the Middleman partial.

require "fileutils"
require "open3"
require "tmpdir"
require "yaml"

ROOT = File.expand_path("..", __dir__)
DEFAULT_SOURCE_DIR = File.expand_path("~/Downloads/vegetables")
OUTPUT_DIR = File.join(ROOT, "source/assets/images/vegetables")
DATA_PATH = File.join(ROOT, "data/vegetables.yml")
CANVAS_SIZE = 512
QUALITY = 82
IMAGE_EXTENSIONS = %w[.jpg .jpeg .png .webp].freeze

class VegetablePreparationError < StandardError; end

def require_magick!
  return if system("magick", "-version", out: File::NULL, err: File::NULL)

  raise VegetablePreparationError, "ImageMagick is required. Install it with `brew install imagemagick` on macOS."
end

def image_file?(path)
  File.file?(path) && IMAGE_EXTENSIONS.include?(File.extname(path).downcase)
end

def source_dir
  File.expand_path(ARGV.fetch(0, DEFAULT_SOURCE_DIR))
end

def source_paths(dir)
  raise VegetablePreparationError, "Source directory not found: #{dir}" unless Dir.exist?(dir)

  paths = Dir.children(dir).sort.filter_map do |name|
    path = File.join(dir, name)
    path if image_file?(path)
  end

  raise VegetablePreparationError, "No source images found in #{dir}" if paths.empty?

  paths
end

def output_basename(source, index)
  slug = File.basename(source, File.extname(source))
    .downcase
    .gsub(/[^a-z0-9]+/, "-")
    .gsub(/\A-|-\z/, "")

  format("vegetable-%02d-%s.webp", index + 1, slug)
end

def optimize_image(source, destination)
  stdout, stderr, status = Open3.capture3(
    "magick",
    source,
    "-auto-orient",
    "-background", "none",
    "-alpha", "on",
    "-trim", "+repage",
    "-resize", "#{CANVAS_SIZE}x#{CANVAS_SIZE}>",
    "-gravity", "center",
    "-extent", "#{CANVAS_SIZE}x#{CANVAS_SIZE}",
    "-strip",
    "-define", "webp:method=6",
    "-define", "webp:alpha-quality=90",
    "-quality", QUALITY.to_s,
    destination
  )

  return if status.success?

  raise VegetablePreparationError, "Could not optimize #{source}: #{stdout}#{stderr}"
end

def write_data(entries)
  payload = entries.map do |entry|
    {
      "image" => "vegetables/#{entry.fetch(:basename)}",
      "source" => entry.fetch(:source)
    }
  end

  yaml = payload.to_yaml.sub(/\A---\n/, "")
  File.write(
    DATA_PATH,
    "# Generated by scripts/prepare_vegetable_images.rb\n" \
      "# Run: ruby scripts/prepare_vegetable_images.rb [source_directory]\n" \
      "#{yaml}"
  )
end

def total_size(paths)
  paths.sum { |path| File.size(path) }
end

def human_size(bytes)
  units = %w[B KB MB GB]
  size = bytes.to_f
  unit = units.shift

  while size >= 1024 && units.any?
    size /= 1024
    unit = units.shift
  end

  format("%.1f %s", size, unit)
end

begin
  require_magick!

  sources = source_paths(source_dir)
  entries = []
  generated_paths = []

  Dir.mktmpdir("vegetables-optimized") do |temp_dir|
    sources.each_with_index do |source, index|
      basename = output_basename(source, index)
      output = File.join(temp_dir, basename)
      optimize_image(source, output)
      generated_paths << output
      entries << { basename: basename, source: File.basename(source) }
    end

    original_size = total_size(sources)
    optimized_size = total_size(generated_paths)

    FileUtils.rm_rf(OUTPUT_DIR)
    FileUtils.mkdir_p(OUTPUT_DIR)

    generated_paths.each do |path|
      FileUtils.cp(path, File.join(OUTPUT_DIR, File.basename(path)))
    end

    write_data(entries)

    puts "Prepared #{entries.size} vegetable images."
    puts "Source images: #{human_size(original_size)} in #{source_dir}"
    puts "Optimized WebP images: #{human_size(optimized_size)} in #{OUTPUT_DIR}"
  end
rescue VegetablePreparationError => error
  warn error.message
  exit 1
end
